/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_easyar_samples_helloarvideo_DataProvider */

#ifndef _Included_cn_easyar_samples_helloarvideo_DataProvider
#define _Included_cn_easyar_samples_helloarvideo_DataProvider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_easyar_samples_helloarvideo_DataProvider
 * Method:    callMethod1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_easyar_samples_helloarvideo_DataProvider_callMethod1
  (JNIEnv *, jobject);

/*
 * Class:     cn_easyar_samples_helloarvideo_DataProvider
 * Method:    callMethod2
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_easyar_samples_helloarvideo_DataProvider_callMethod2
  (JNIEnv *, jobject);

/*
 * Class:     cn_easyar_samples_helloarvideo_DataProvider
 * Method:    callMethod3
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_easyar_samples_helloarvideo_DataProvider_callMethod3
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
